# Generated by Django 5.1.1 on 2024-09-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transport_type',
            field=models.CharField(choices=[('flight', 'Flight'), ('bus', 'Bus')], default='flight', max_length=10),
        ),
    ]
