# Generated by Django 4.2.13 on 2024-09-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_customer_age_booking_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
